root - 27-Sep-23 02:13:41 - ERROR - Internal Server Error!!!: Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/generics.py", line 199, in get
    return self.list(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
                                    ^^^^^^^^^^^^^^^^^^^
  File "/medicalapp/hrecords/views.py", line 21, in get_queryset
    raise Exception("Annoying Error!!")
Exception: Annoying Error!!

root - 27-Sep-23 02:13:41 - ERROR - Internal Server Error!!!: <JsonResponse status_code=500, "application/json">
django.request - 27-Sep-23 02:13:41 - ERROR - Not Implemented: /api/v1.0/records/
medicalapp - 2023-09-27 02:19:07,895 - WARNING - This is a warning
medicalapp - 2023-09-27 02:19:07,896 - ERROR - This is an error
django.utils.autoreload - 27-Sep-23 02:45:36 - INFO - /medicalapp/manage.py changed, reloading.
medicalapp - 2023-09-27 02:56:56,754 - WARNING - This is a warning
medicalapp - 2023-09-27 02:56:56,760 - ERROR - This is an error
drf_yasg.inspectors.base - 27-Sep-23 02:57:06 - WARNING - view's RecordDetailAPIView raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
           ^^^^^^^^^^^^^
  File "/medicalapp/hrecords/views.py", line 53, in get_queryset
    urlparam: dict = URLParams.model_validate(self.kwargs).model_dump()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pydantic/main.py", line 503, in model_validate
    return cls.__pydantic_validator__.validate_python(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for URLParams
pk
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.4/v/missing
django.utils.autoreload - 27-Sep-23 03:20:02 - INFO - /medicalapp/hrecords/views.py changed, reloading.
medicalapp - 2023-09-27 03:20:07,605 - WARNING - This is a warning
medicalapp - 2023-09-27 03:20:07,607 - ERROR - This is an error
django.utils.autoreload - 27-Sep-23 03:20:15 - INFO - /medicalapp/medicalapp/settings.py changed, reloading.
medicalapp - 2023-09-27 03:20:19,783 - WARNING - This is a warning
medicalapp - 2023-09-27 03:20:19,784 - ERROR - This is an error
medicalapp - 2023-09-27 04:20:36,583 - WARNING - This is a warning
medicalapp - 2023-09-27 04:20:36,583 - ERROR - This is an error
django.utils.autoreload - 27-Sep-23 03:23:21 - INFO - /medicalapp/users/migrations/0001_initial.py changed, reloading.
medicalapp - 2023-09-27 03:23:28,843 - WARNING - This is a warning
medicalapp - 2023-09-27 03:23:28,846 - ERROR - This is an error
medicalapp - 2023-09-27 04:28:25,554 - WARNING - This is a warning
medicalapp - 2023-09-27 04:28:25,554 - ERROR - This is an error
medicalapp - 2023-09-27 04:29:02,641 - WARNING - This is a warning
medicalapp - 2023-09-27 04:29:02,641 - ERROR - This is an error
medicalapp - 2023-09-27 04:30:21,897 - WARNING - This is a warning
medicalapp - 2023-09-27 04:30:21,898 - ERROR - This is an error
medicalapp - 2023-09-27 04:30:36,637 - WARNING - This is a warning
medicalapp - 2023-09-27 04:30:36,637 - ERROR - This is an error
medicalapp - 2023-09-27 04:31:09,542 - WARNING - This is a warning
medicalapp - 2023-09-27 04:31:09,542 - ERROR - This is an error
medicalapp - 2023-09-27 04:33:09,903 - WARNING - This is a warning
medicalapp - 2023-09-27 04:33:09,904 - ERROR - This is an error
medicalapp - 2023-09-27 04:36:50,316 - WARNING - This is a warning
medicalapp - 2023-09-27 04:36:50,316 - ERROR - This is an error
medicalapp - 2023-09-27 04:38:45,323 - WARNING - This is a warning
medicalapp - 2023-09-27 04:38:45,323 - ERROR - This is an error
medicalapp - 2023-09-27 04:39:32,013 - WARNING - This is a warning
medicalapp - 2023-09-27 04:39:32,013 - ERROR - This is an error
medicalapp - 2023-09-27 04:40:38,324 - WARNING - This is a warning
medicalapp - 2023-09-27 04:40:38,324 - ERROR - This is an error
medicalapp - 2023-09-27 04:41:30,220 - WARNING - This is a warning
medicalapp - 2023-09-27 04:41:30,220 - ERROR - This is an error
medicalapp - 2023-09-27 04:43:09,445 - WARNING - This is a warning
medicalapp - 2023-09-27 04:43:09,446 - ERROR - This is an error
medicalapp - 2023-09-27 04:43:34,576 - WARNING - This is a warning
medicalapp - 2023-09-27 04:43:34,576 - ERROR - This is an error
medicalapp - 2023-09-27 04:44:10,901 - WARNING - This is a warning
medicalapp - 2023-09-27 04:44:10,901 - ERROR - This is an error
django.utils.autoreload - 27-Sep-23 03:45:12 - INFO - /medicalapp/medicalapp/logger.py changed, reloading.
django.utils.autoreload - 27-Sep-23 03:47:28 - INFO - /medicalapp/medicalapp/settings.py changed, reloading.
django.utils.autoreload - 27-Sep-23 03:50:00 - INFO - /medicalapp/medicalapp/errorhandler.py changed, reloading.
django.request - 27-Sep-23 04:12:05 - WARNING - Bad Request: /api/v1.0/auth/login
django.request - 27-Sep-23 06:41:34 - WARNING - Bad Request: /api/v1.0/auth/login
django.request - 27-Sep-23 06:41:47 - WARNING - Bad Request: /api/v1.0/auth/register
django.request - 27-Sep-23 06:42:18 - WARNING - Bad Request: /api/v1.0/auth/login
django.utils.autoreload - 27-Sep-23 06:57:55 - INFO - /medicalapp/medicalapp/settings.py changed, reloading.
django.utils.autoreload - 27-Sep-23 07:02:16 - INFO - /medicalapp/medicalapp/settings.py changed, reloading.
